COMMENT =		Memory Efficient Serialization

V =			1.5.0
DISTNAME =		flatbuffers-${V}
CATEGORIES =		devel
HOMEPAGE =		http://google.github.io/flatbuffers/
MAINTAINER =		Pascal S. de Kloe <pascal@quies.net>

MASTER_SITES =		https://github.com/google/flatbuffers/archive/
DISTFILES =		v${V}.tar.gz
DIST_SUBDIR =		flatbuffers
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c m

MODULES =		devel/cmake gcc4
MODGCC4_ARCHS =		*
MODGCC4_LANGS =		c++

.include <bsd.port.mk>
